name: Build Navoa Multiplatform App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android armv7-linux-androideabi x86_64-linux-android

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Instalar flutter_rust_bridge_codegen e cargo-ndk
        run: |
          cargo install "flutter_rust_bridge_codegen@^2.0.0"
          cargo install cargo-ndk

      - name: Gerar Bindings do Rust para Flutter
        run: flutter_rust_bridge_codegen generate

      - name: Instalar dependências do Flutter
        run: flutter pub get

      - name: Compilar APK Android
        run: flutter build apk --release

      - name: Guardar APK como Artefacto
        uses: actions/upload-artifact@v4
        with:
          name: Navoa-Android-APK
          path: build/app/outputs/flutter-apk/app-release.apk
